; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	D:\Projects\ASU\ICPDAS\TMMiniOS\TMMiniOS\UserCount.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?UserCount@@YAXXZ				; UserCount
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?UserCount@@YAXXZ
_TEXT	SEGMENT
?UserCount@@YAXXZ PROC					; UserCount, COMDAT
; File d:\projects\asu\icpdas\tmminios\tmminios\usercount.cpp
; Line 16
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 18
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?UserCount@@YAXXZ ENDP					; UserCount
_TEXT	ENDS
END
