; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	D:\Projects\ASU\ICPDAS\TMMiniOS\TMMiniOS\v7000.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
